#!/usr/bin/env bash
# Install a persistent SSH tunnel (systemd user service) for split-host hosting.
#
# Use when Cursor Voice runs on a remote host/container but Tailscale Serve runs
# on this machine (e.g. eva → debian incus :5671).
#
# Usage:
#   bash scripts/install-remote-tunnel.sh
#   bash scripts/install-remote-tunnel.sh --remote borys@100.118.238.2 --remote-port 5671 --local-port 15671
#
# After install:
#   tailscale serve --bg http://127.0.0.1:15671   # once, on this machine
#   systemctl --user status cursor-voice-tunnel
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

REMOTE_SSH="${REMOTE_SSH:-borys@100.118.238.2}"
REMOTE_BIND_PORT="${REMOTE_BIND_PORT:-5671}"
LOCAL_BIND_PORT="${LOCAL_BIND_PORT:-15671}"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --remote) REMOTE_SSH="$2"; shift 2 ;;
    --remote-port) REMOTE_BIND_PORT="$2"; shift 2 ;;
    --local-port) LOCAL_BIND_PORT="$2"; shift 2 ;;
    -h|--help)
      sed -n '2,20p' "$0" | sed 's/^# \?//'
      exit 0
      ;;
    *) echo "Unknown option: $1" >&2; exit 1 ;;
  esac
done

TUNNEL_DIR="${HOME}/.config/cursor-voice"
ENV_FILE="${TUNNEL_DIR}/tunnel.env"
SERVICE_DIR="${HOME}/.config/systemd/user"
SERVICE_FILE="${SERVICE_DIR}/cursor-voice-tunnel.service"
TUNNEL_SCRIPT="${PROJECT_DIR}/scripts/ssh-remote-tunnel.sh"

mkdir -p "$TUNNEL_DIR" "$SERVICE_DIR"
chmod +x "$TUNNEL_SCRIPT"

cat > "$ENV_FILE" <<EOF
# Generated by scripts/install-remote-tunnel.sh — edit as needed
REMOTE_SSH=${REMOTE_SSH}
REMOTE_BIND_HOST=127.0.0.1
REMOTE_BIND_PORT=${REMOTE_BIND_PORT}
LOCAL_BIND_HOST=127.0.0.1
LOCAL_BIND_PORT=${LOCAL_BIND_PORT}
EOF
chmod 600 "$ENV_FILE"

cat > "$SERVICE_FILE" <<EOF
[Unit]
Description=Cursor Voice SSH tunnel (${LOCAL_BIND_PORT} → ${REMOTE_SSH}:${REMOTE_BIND_PORT})
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
Environment=CURSOR_VOICE_TUNNEL_ENV=${ENV_FILE}
ExecStart=${TUNNEL_SCRIPT}
Restart=always
RestartSec=5
StartLimitIntervalSec=0

[Install]
WantedBy=default.target
EOF

systemctl --user daemon-reload
systemctl --user enable --now cursor-voice-tunnel.service

sleep 2
if curl -sf --max-time 5 "http://127.0.0.1:${LOCAL_BIND_PORT}/healthz" >/dev/null; then
  echo "OK: tunnel healthy at http://127.0.0.1:${LOCAL_BIND_PORT}/healthz"
else
  echo "WARN: tunnel service started but health check failed — check:" >&2
  echo "  journalctl --user -u cursor-voice-tunnel -n 30" >&2
  exit 1
fi

echo ""
echo "Tunnel installed. Ensure Tailscale Serve points at the local port:"
echo "  tailscale serve --bg http://127.0.0.1:${LOCAL_BIND_PORT}"
echo ""
echo "Status: systemctl --user status cursor-voice-tunnel"
